apiVersion: apps/v1
kind: Deployment
metadata:
  name: piedge-gui
  namespace: pi-edge-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piedge-gui
  template:
    metadata:
      labels:
        app: piedge-gui
    spec:
      containers:
        - name: gui
          image: piedge/gui:1.0.9
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
      nodeSelector:
        kubernetes.io/hostname: zorro-solutions

---

apiVersion: v1
kind: Service
metadata:
  name: gui-svc
  namespace: pi-edge-system
spec:
  selector:
    app: piedge-gui
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5173
  type: NodePort